// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
const go = {
  "main": {
    "App": {
      /**
       * GetCurrentFile
       * @returns {Promise<string>}  - Go Type: string
       */
      "GetCurrentFile": () => {
        return window.go.main.App.GetCurrentFile();
      },
      /**
       * New
       * @param {Array<number>} arg1 - Go Type: []uint8
       * @returns {Promise<boolean>}  - Go Type: bool
       */
      "New": (arg1) => {
        return window.go.main.App.New(arg1);
      },
      /**
       * Open
       * @returns {Promise<boolean>}  - Go Type: bool
       */
      "Open": () => {
        return window.go.main.App.Open();
      },
      /**
       * Save
       * @returns {Promise<boolean>}  - Go Type: bool
       */
      "Save": () => {
        return window.go.main.App.Save();
      },
    },
  },

};
export default go;
