// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Alert(arg1:string,arg2:string):void;

export function GetCurrentFile():Promise<string>;

export function New(arg1:Array<number>):Promise<boolean>;

export function Open():Promise<boolean>;

export function Save():Promise<boolean>;
