// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Alert(arg1, arg2) {
  return window['go']['main']['App']['Alert'](arg1, arg2);
}

export function GetCurrentFile() {
  return window['go']['main']['App']['GetCurrentFile']();
}

export function New(arg1) {
  return window['go']['main']['App']['New'](arg1);
}

export function Open() {
  return window['go']['main']['App']['Open']();
}

export function Save() {
  return window['go']['main']['App']['Save']();
}
